markdown: kramdown
title: CMS Supplier Directory (prototype)
description: A prototype of the forthcoming CMS Supplier Directory
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- README.md
- go

permalink: pretty
highlighter: rouge
kramdown:
  auto_ids: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Andrew Maier
  url: https://bellese.github.io/cms-supplier-directory

github:
  organization: bellese
  repository: cms-supplier-directory
  default_branch: master

collections:
  pages:
    output: true
    permalink: /:path/

generate_nodes: true
flat_namespace: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

repos:
- name: 18F Content Guide
  description: Main repository
  url: https://github.com/18F/content-guide
